### ISSUE TITLE
company inserts "raw" candidation into buffer.

### ISSUE THREAD

**Issue by madper** [cquery-project/emacs-cquery#1]
Hey Ray,

With cquery, I got `oom_kill_process(${1:struct oom_control *oc}, ${2:const char *message})$0` in my capf list.
> http://paste.ubuntu.com.cn/i4293366
It seems the raw format should be sent to Yas. Somehow it directly showed to end user.

I'm still debugging my configuration.

BR,
M

**Comment by MaskRay** [comment]
Hi No Money,

You may try company-lsp
```elisp
(setq company-lsp-async t
          company-lsp-cache-candidates nil)
```

BR,
R

**Comment by madper** [comment]
company-lsp works. thanks a lot!
Let me close the issue ticket.
