### ISSUE TITLE
Snippet expansion partially broken?

### ISSUE THREAD

**Issue by Sarcasm** [cquery-project/emacs-cquery#10]
I'm not sure this is an issue with emacs-cquery, but when I do completion in a clean Emacs, I have the feeling snippets aren't available at first.
If I revert the buffer and try again, it seems to work.

Can you reproduce the issue?
I'm not sure, but I don't think I noticed this issue initially.

Is it possible that one of the recent commit in cquery triggered this?
- https://github.com/jacobdufault/cquery/commit/455423f2b855325ba7ebb54535aa1a5db0676db5
- https://github.com/jacobdufault/cquery/commit/7942274e10ab66adf473a5bc88205ba56ea7a4e2

**Comment by MaskRay** [comment]
The two commits address issues when an editor does not support snippets (`snippetSupport: false`). lsp-mode announces it supports snippets (check with `M-x lsp-capabilities`) so the two commits should have no effect.

**Comment by Sarcasm** [comment]
Sorry for this bug report, it was due to my config.
When my Emacs start, I enable yasnippet "lazily" after some idle time.
I guess LSP does not like it when yasnippet is enabled/disabled dynamically.
