### ISSUE TITLE
Restart cquery after crash

### ISSUE THREAD

**Issue by clearmisp** [cquery-project/emacs-cquery#15]
How do I restart lsp-cquery after a crash? I sometimes see the following errors in Emacs;

```
/home/micke/devel/projects/LCC/: lsp-cquery has exited (segmentation fault (core dumped)
)
error in process sentinel: lsp--uninitialize-workspace: Process lsp-cquery is not active
error in process sentinel: Process lsp-cquery is not active
lsp--send-wait: Timed out while waiting for a response from the language server
Error in ‘lsp--on-hover’: (error "Process lsp-cquery not running") [3 times]
Error running timer ‘lsp-ui-sideline--run’: (error "Process lsp-cquery not running")
```
The only way to get cquery up and running again that I know of is to restart Emacs. Is there another way to restart cquery without leaving the Emacs session?

**Comment by MaskRay** [comment]
I `C-x C-b` and delete all buffers associated with a lsp-mode workspace.

**Comment by myrgy** [comment]
is it possible to add some command that will start cquery if it's not running?

**Comment by MaskRay** [comment]
Thanks for reporting this. I think this has been implemented by lsp-mode in https://github.com/emacs-lsp/lsp-mode/pull/290/files

Probably `M-x lsp-restart-workspace` in case the server dies.
