### ISSUE TITLE
Is it possible to get compilation arguments / flags from emacs cquery?

### ISSUE THREAD

**Issue by alexmurray** [cquery-project/emacs-cquery#17]
I currently maintain [flycheck-clang-analyzer](https://github.com/alexmurray/flycheck-clang-analyzer) which allows to run the clang static analysis using the current files compilation options via either [irony](https://github.com/Sarcasm/irony-mode) or [rtags](https://github.com/Andersbakken/rtags). It would be great to add support for using cquery as well - is there a way to call into emacs-cquery to get the compilation flags etc for the current file?

**Comment by jacobdufault** [comment]
Sure, we can expose a custom LSP message. Can you file a bug in the main cquery repository as well?

**Comment by MaskRay** [comment]
Close via 122f4f7d61594762520864f323bd83ee26b8b255

```elisp
(gethash "args" (cquery-file-info))
```

**Comment by alexmurray** [comment]
Wow, thank you for the very quick response and implementation - truly amazing!
