### ISSUE TITLE
See type hierarchy, finding base/derived methods/classes

### ISSUE THREAD

**Issue by clearmisp** [cquery-project/emacs-cquery#18]
The cquery server is able to return info on a types hierarchy (parent type, derived types, expandable tree view), finding base/derived methods/classes and presenting a call tree.

I searched through available Emacs commands and found the function **cquery-call-tree** which seem to return a call tree for a symbol at point, this works. But I fail to find a way to see a type hierarchy for symbol at point, or finding derived methods etc. Are these not implemented? What is the best way discussing topics like this for emacs lsp using cquery? It doesn't feel right  to submit an issue here just to query for basic functionality when there's not an actual bug involved.

**Comment by jacobdufault** [comment]
@MaskRay 

Feel free to hangout in https://gitter.im/cquery-project/Lobby

**Comment by MaskRay** [comment]
Yes, emacs-cquery has not implemented this feature.

https://github.com/emacs-lsp/lsp-ui/issues/73

**Comment by MaskRay** [comment]
These hierarchies are now implemented in emacs-cquery.

You may find my config useful https://github.com/MaskRay/Config/blob/master/home/.emacs.d/private/%2Bmy/my-code/packages.el#L243
