### ISSUE TITLE
On windows there is mess code in cquery-tree--make-prefix 

### ISSUE THREAD

**Issue by zijianyue** [cquery-project/emacs-cquery#19]
![image](https://user-images.githubusercontent.com/6119928/36670951-efe8c924-1b34-11e8-81a5-5af681a19928.png)

![image](https://user-images.githubusercontent.com/6119928/36706301-44fe2016-1ba4-11e8-9ec9-237c1492fd3f.png)

**Comment by MaskRay** [comment]
GBK mess is non-issue.
