### ISSUE TITLE
Preprocesssed file

### ISSUE THREAD

**Issue by myrgy** [cquery-project/emacs-cquery#22]
It might be great to have function to show preprocessed translation unit.
I know that I can ask compiler to do that, but it would be more convinient to do that via cquery. Seems like rtags has this feature.

**Comment by MaskRay** [comment]
I think this can be implemented based on:
```elisp
(ht-get (cquery-file-info) "args")
```

**Comment by MaskRay** [comment]
commit f975f02794b910f5501e4d4efee82e563b3bd1c4

I don't know how to it work on a region as rtags-preprocess-file supports..

**Comment by myrgy** [comment]
Full file is fine for me! Thanks a lot!
