### ISSUE TITLE
when-let* Symbol's function definition is void

### ISSUE THREAD

**Issue by anderslanglands** [cquery-project/emacs-cquery#25]
Hi, I get the following errors when using emacs-cquery from head:

```
error in process filter: progn: Symbol’s function definition is void: when-let*
error in process filter: Symbol’s function definition is void: when-let*
```

This is with emacs 25.3.1. I looked around a bit and it seems these functions were provided by dash, which I've tried installing manually, but I still get the errors.

**Comment by anderslanglands** [comment]
Modifying the two instances of "when-let" to be "-when-let" in cquery-semantic-highlighting.el fixes the issue.

**Comment by MaskRay** [comment]
The latest version does not use `when-let` (which will be an alias of `when-let*` in the 26 release https://github.com/emacs-mirror/emacs/commit/af4697faa1f5b643f63a9ea61aa205a4c1432e23)

**Comment by ambihelical** [comment]
There are some additional calls in cquery-tree.el, for example cquery-quit. Are you saying we need to update to 26 in order for emacs-cquery to function correctly?

**Comment by MaskRay** [comment]
I checked that `when-let*` does not exist in 'subr-x.el` shipped with Emacs 25, so we should use `-when-let*`. Fixed
