### ISSUE TITLE
font-lock renders unwanted bg color after xref-find-definitions

### ISSUE THREAD

**Issue by amosbird** [cquery-project/emacs-cquery#30]
![](https://la.wentropy.com/XWU3.png)

This doesn't happen to `overlay`, however `overlay` is still extremely slow even with the patch mentioned here https://lists.gnu.org/archive/html/emacs-devel/2018-03/msg00776.html

**Comment by MaskRay** [comment]
I saw this yesteday. Can you print the text properties?

The font-lock semantic highlighting code

https://github.com/cquery-project/emacs-cquery/blob/master/cquery-semantic-highlighting.el#L280

**Comment by amosbird** [comment]
```
There are text properties here:
  face                 (font-lock-variable-name-face highlight highlight)
  font-lock-face       (font-lock-variable-name-face highlight highlight)
  fontified            t
```

it's trivial to reproduce.  using emacs source code `/home/amos/git/emacs/src/xdisp.c:15634` jump to `window_height`

**Comment by sebastiencs** [comment]
That's a bug in lsp-mode, I made a PR to fix it

**Comment by amosbird** [comment]
thanks.
