### ISSUE TITLE
Symbol highlighting + flycheck error

### ISSUE THREAD

**Issue by innerout** [cquery-project/emacs-cquery#37]
This error probably should be reported in the cquery repo but i am not sure.
Suppose we have for example the code below to explain the error.

```
int main(void){
    int hash;
    hash = 1;
    return 0;
}
```
If i rename the hash variable to something else like hash_value and fix the ```hash = 1``` line to match the new name sometimes it will not find that i have typed the correct name in the buffer and report unknown variable hash_valu while i have typed the variable correctly.(Wrong typing the name of the variable in the last sentence is intentional its the way cquery reports usually the wrong name)
In addition to that symbol highlighting stops working after that in the buffer and flycheck starts reporting errors in irrelevant places that have no errors.
Usually the error occurs after renaming a variable.
The error happens randomly after coding some time in a session.
I have Arch linux with Emacs 25.3.1 and [cquery](https://aur.archlinux.org/packages/cquery/) package from aur.

**Comment by jacobdufault** [comment]
Can you refile on the main cquery repro?
