### ISSUE TITLE
order of completion candidates

### ISSUE THREAD

**Issue by Dickby** [cquery-project/emacs-cquery#38]
Is it just me or is the order of the completion candidates "upside down"? the best matching candidates are always last in the candidate list. I use company-lsp, perhaps this is an problem of that package?
Thanks

**Comment by jacobdufault** [comment]
It's possible cquery is ordering completions incorrectly, but I think it is more likely a bug in your config since vscode/etc work correctly. Try commenting out these lines

https://github.com/cquery-project/cquery/blob/master/src/messages/text_document_completion.cc#L204-L206

**Comment by Dickby** [comment]
This changes nothing. i assume than it's a problem with my configuration!?

**Comment by jacobdufault** [comment]
Yes, most likely.

**Comment by Dickby** [comment]
It actually is my configuration, thanks for the information and for this excellent package.

**Comment by jacobdufault** [comment]
:), may I ask what was wrong?

**Comment by Dickby** [comment]
Because i had trouble with company-lsp from the beginning i tried to set
`company-transformers` to nil, as i saw in cquery-project/cquery#434 .
By removing that and using company-statistics i finally have a setup that works for me.
Thanks again.
