### ISSUE TITLE
replace c-mode-common-hook with c-c++-mode-hooks

### ISSUE THREAD

**Issue by ztlevi** [cquery-project/emacs-cquery#39]
`c-mode-common-hook` will affect `java-mode-hook` as well. That is not expected and will case `Error from the Language Server: Unable to find file`.

Better to use `c-c++-mode-hooks` instead.

**Comment by jacobdufault** [comment]
PR appreciated :)

**Comment by innerout** [comment]
You can close this issue it is solved.
