### ISSUE TITLE
cquery--read-range: End of buffer

### ISSUE THREAD

**Issue by andschwa** [cquery-project/emacs-cquery#48]
I am getting the error `error in process filter: cquery--read-range: End of buffer` occasionally. Any ideas? I'll add more info as I gather it.

**Comment by dscole** [comment]
I'm getting the same error as well, and I think it's causing emacs to hang for a little bit each time.

**Comment by andyleejordan** [comment]
There's been no movement on this issue for two years, and since I opened it, I'm going to close it 😉
